"""Generate the physics/geometry documentation figures at tiny resolution.

Every figure is reproducible from this script and lands compressed (< 150 kB)
under ``docs/_static/figures/docs/``. The pages that embed them are
:doc:`geometry`, :doc:`numerics`, and :doc:`physics_reference`.

Figures
-------
``bmag_contour_w7x.png``
    ``|B|`` on one field period of a W7-X-like flux surface, evaluated
    analytically from :meth:`dkx.magnetic_geometry.FluxSurfaceGeometry.from_scheme`
    (``geometryScheme = 4``, the Beidler et al. NF 51 (2011) harmonic table).
    No kinetic solve is involved: the map is a closed-form Boozer spectrum.

``transport_coeff_vs_collisionality.png``
    Monoenergetic (``RHSMode = 3``) transport-matrix entries versus normalized
    collisionality ``nuPrime`` for a three-helicity model field
    (``geometryScheme = 1``). Reproduces the physics of
    ``examples/transport/transport_coefficients.py`` at documentation resolution.

``ambipolar_er_roots.png``
    Species radial fluxes and the radial current ``J_r(E_r) = sum_s Z_s Gamma_s``
    for an ion + electron pair, with the ambipolar root marked. Reproduces
    ``examples/vmex_finite_beta/ambipolar_er_scan.py`` at documentation resolution.

Run
---
    python docs/figures/generate_docs_figures.py

Set ``DKX_DOCS_FIGS_TINY=1`` for the smallest grids (used in CI smoke
runs); the default grids are still small enough for a laptop CPU.
"""

from __future__ import annotations

import os
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "docs" / "_static" / "figures" / "docs"
SIZE_BUDGET_KB = 150.0
TINY = os.environ.get("DKX_DOCS_FIGS_TINY") == "1"

# Palette (shared with tools/benchmarks/readme_figures.py; color follows the code).
BLUE = "#2a78d6"
ORANGE = "#eb6834"
GREEN = "#2e9e6b"
INK = "#0b0b0b"
INK_2 = "#52514e"
GRID = "#e4e3df"


def _style_axes(ax: plt.Axes) -> None:
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(GRID)
    ax.tick_params(colors=INK_2, labelsize=8.5)


def _report(path: Path) -> None:
    size_kb = path.stat().st_size / 1024.0
    print(f"wrote {path.relative_to(REPO_ROOT)} ({size_kb:.1f} kB)")
    if size_kb > SIZE_BUDGET_KB:
        raise SystemExit(f"{path} exceeds the {SIZE_BUDGET_KB:.0f} kB documentation figure budget")


# ---------------------------------------------------------------------------
# 1) |B| contour on a W7-X-like flux surface (analytic Boozer spectrum)
# ---------------------------------------------------------------------------
def bmag_contour_w7x(path: Path) -> None:
    from dkx.magnetic_geometry import FluxSurfaceGeometry

    n_theta = 64 if not TINY else 32
    n_zeta = 64 if not TINY else 32
    theta = np.linspace(0.0, 2.0 * np.pi, n_theta)
    # Scheme 4 is the W7-X standard table with five field periods; show one period.
    geom = FluxSurfaceGeometry.from_scheme(
        4, theta=np.asarray(theta), zeta=np.asarray(np.linspace(0.0, 2.0 * np.pi / 5.0, n_zeta))
    )
    n_periods = int(geom.n_periods)
    zeta = np.linspace(0.0, 2.0 * np.pi / n_periods, n_zeta)
    b_hat = np.asarray(geom.b_hat)  # (n_theta, n_zeta)

    fig, ax = plt.subplots(figsize=(6.4, 3.7))
    tt, zz = np.meshgrid(theta, zeta, indexing="ij")
    cf = ax.contourf(zz, tt, b_hat, levels=18, cmap="viridis")
    cs = ax.contour(zz, tt, b_hat, levels=9, colors="white", linewidths=0.4, alpha=0.6)
    ax.clabel(cs, inline=True, fontsize=6, fmt="%.2f")
    cbar = fig.colorbar(cf, ax=ax, pad=0.02)
    cbar.set_label(r"$\hat B = B/\bar B$", fontsize=9, color=INK_2)
    cbar.ax.tick_params(labelsize=8, colors=INK_2)
    ax.set_xlabel(r"Boozer toroidal angle $\zeta$ (one field period)", fontsize=9, color=INK_2)
    ax.set_ylabel(r"Boozer poloidal angle $\theta$", fontsize=9, color=INK_2)
    ax.set_title(
        rf"$\hat B(\theta,\zeta)$ on a W7-X-like surface (geometryScheme 4, $N_p={n_periods}$)",
        fontsize=10, color=INK,
    )
    ax.tick_params(colors=INK_2, labelsize=8.5)
    fig.tight_layout()
    fig.savefig(path, dpi=115, bbox_inches="tight", facecolor="white")
    plt.close(fig)


# ---------------------------------------------------------------------------
# 2) Monoenergetic transport coefficients versus collisionality (RHSMode 3)
# ---------------------------------------------------------------------------
_TRANSPORT_DECK = """! RHSMode=3 deck generated by docs/figures/generate_docs_figures.py
&general
  RHSMode = 3
/
&geometryParameters
  geometryScheme = 1
  epsilon_t = -0.07053
  epsilon_h = 0.05067
  iota = 0.4542
  GHat = 3.7481
  IHat = 0.0
  helicity_l = 2
  helicity_n = 10
  B0OverBBar = 1.0
/
&speciesParameters
/
&physicsParameters
  nuPrime = {nu_prime}
  EStar = 0.0
  collisionOperator = 1
  includeXDotTerm = .false.
  includeElectricFieldTermInXiDot = .false.
  useDKESExBDrift = .true.
  includePhi1 = .false.
/
&resolutionParameters
  Ntheta = {n_theta}
  Nzeta = {n_zeta}
  Nxi = {n_xi}
  NL = 4
  Nx = 1
  solverTolerance = 1d-10
/
&otherNumericalParameters
  Nxi_for_x_option = 0
/
"""


def transport_coeff_vs_collisionality(path: Path, work_dir: Path) -> None:
    from dkx.run import run_transport_matrix

    n_points = 4 if TINY else 6
    nu_primes = np.logspace(-2.5, -0.5, n_points)
    n_theta = 9 if TINY else 13
    n_zeta = 9 if TINY else 13
    n_xi = 10 if TINY else 18

    matrices = []
    for i, nu_prime in enumerate(nu_primes):
        deck = work_dir / f"transport_docs.nu{i}.input.namelist"
        deck.write_text(
            _TRANSPORT_DECK.format(nu_prime=nu_prime, n_theta=n_theta, n_zeta=n_zeta, n_xi=n_xi)
        )
        t0 = time.perf_counter()
        run = run_transport_matrix(deck, solve_method="auto", emit=None)
        matrices.append(np.asarray(run.transport_matrix))
        print(f"  nuPrime={nu_prime:.3e}  L11={matrices[-1][0, 0]:.3e}  ({time.perf_counter() - t0:.2f} s)")
    matrices = np.asarray(matrices)

    fig, ax = plt.subplots(figsize=(6.0, 4.0))
    ax.loglog(nu_primes, np.abs(matrices[:, 0, 0]), "o-", color=BLUE,
              label=r"$|L_{11}|$  (radial, $D_{11}$-like)")
    ax.loglog(nu_primes, np.abs(matrices[:, 1, 0]), "s-", color=ORANGE,
              label=r"$|L_{21}|$  (bootstrap, $D_{31}$-like)")
    ax.set_xlabel(r"$\nu'$  (normalized collisionality)", fontsize=9.5, color=INK_2)
    ax.set_ylabel("monoenergetic transport coefficient", fontsize=9.5, color=INK_2)
    ax.set_title("RHSMode=3 transport matrix vs collisionality (three-helicity model)",
                 fontsize=9.5, color=INK)
    ax.grid(True, which="both", color=GRID, linewidth=0.7)
    _style_axes(ax)
    ax.legend(fontsize=9, frameon=False)
    fig.tight_layout()
    fig.savefig(path, dpi=130, bbox_inches="tight", facecolor="white")
    plt.close(fig)


# ---------------------------------------------------------------------------
# 3) Ambipolar radial electric field: fluxes and the J_r(E_r) = 0 root
# ---------------------------------------------------------------------------
_AMBIPOLAR_DECK = """! Er-scan deck generated by docs/figures/generate_docs_figures.py
&general
/
&geometryParameters
  geometryScheme = 1
  inputRadialCoordinate = 3
  rN_wish = 0.3
  B0OverBBar = 1.0
  GHat = 1.0
  IHat = 0.0
  iota = 1.31
  epsilon_t = 0.1
  epsilon_h = 0.05
  helicity_l = 2
  helicity_n = 5
  psiAHat = 0.045
  aHat = 0.1
/
&speciesParameters
  Zs = 1 -1
  mHats = 1.0 0.000545509
  nHats = 1.0 1.0
  THats = 1.0 1.0
  dNHatdrHats = -0.5 -0.5
  dTHatdrHats = -1.0 -1.0
/
&physicsParameters
  Delta = 4.5694d-3
  alpha = 1.0
  nu_n = 8.4774d-3
  Er = {er}
  collisionOperator = 1
  includeXDotTerm = .false.
  includeElectricFieldTermInXiDot = .false.
  useDKESExBDrift = .true.
  includePhi1 = .false.
/
&resolutionParameters
  Ntheta = {n_theta}
  Nzeta = {n_zeta}
  Nxi = {n_xi}
  NL = 4
  Nx = {n_x}
  solverTolerance = 1d-10
/
&otherNumericalParameters
  Nxi_for_x_option = 0
/
"""


def ambipolar_er_roots(path: Path, work_dir: Path) -> None:
    from dkx import er as er_solver

    er_bracket = (-3.0, 1.0)
    er_scan = np.linspace(*er_bracket, 5 if TINY else 7)
    n_theta = 7 if TINY else 9
    n_zeta = 7 if TINY else 9
    n_xi = 8 if TINY else 12
    n_x = 3 if TINY else 4

    def write_deck(er: float) -> Path:
        deck = work_dir / "ambipolar_docs.input.namelist"
        deck.write_text(
            _AMBIPOLAR_DECK.format(er=er, n_theta=n_theta, n_zeta=n_zeta, n_xi=n_xi, n_x=n_x)
        )
        return deck

    problem = er_solver.prepare(write_deck(0.0), er_bracket=er_bracket)
    scan_gamma, scan_jr, warm = [], [], None
    for er in er_scan:
        j_r, gamma, state = er_solver.radial_current(
            problem, float(er),
            x0=(warm.x if warm else None), recycle=(warm.recycle if warm else None),
        )
        warm = state
        scan_gamma.append(np.asarray(gamma, dtype=np.float64))
        scan_jr.append(float(j_r))
    scan_gamma = np.asarray(scan_gamma)
    scan_jr = np.asarray(scan_jr)

    result = er_solver.find_ambipolar_er(write_deck(0.0), er_bracket=er_bracket, max_iter=20, emit=None)
    er_root = float(result.er)
    print(f"  ambipolar root: Er={er_root:.4f}  ({result.root_type} root, J_r={result.radial_current:.2e})")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9.2, 3.7))
    ax1.plot(er_scan, scan_gamma[:, 0], "o-", color=BLUE, label=r"$\Gamma_i$ (ions)")
    ax1.plot(er_scan, scan_gamma[:, 1], "s-", color=ORANGE, label=r"$\Gamma_e$ (electrons)")
    ax1.axvline(er_root, color=INK, ls="--", lw=1, label=rf"ambipolar $E_r={er_root:.2f}$")
    ax1.set_xlabel(r"$E_r$  (normalized deck units)", fontsize=9.5, color=INK_2)
    ax1.set_ylabel(r"$\Gamma_s$  (particleFlux_vm_psiHat)", fontsize=9.5, color=INK_2)
    ax1.set_title("Species radial fluxes vs $E_r$", fontsize=9.5, color=INK)
    ax1.grid(True, color=GRID, linewidth=0.7)
    _style_axes(ax1)
    ax1.legend(fontsize=8.5, frameon=False)

    ax2.plot(er_scan, scan_jr, "o-", color=GREEN)
    ax2.axhline(0.0, color=INK_2, lw=0.9)
    ax2.plot([er_root], [result.radial_current], "*", color=INK, ms=15,
             label=rf"{result.root_type} root $E_r={er_root:.2f}$")
    ax2.set_xlabel(r"$E_r$", fontsize=9.5, color=INK_2)
    ax2.set_ylabel(r"$J_r = \sum_s Z_s\,\Gamma_s$", fontsize=9.5, color=INK_2)
    ax2.set_title("Radial current and its ambipolar root", fontsize=9.5, color=INK)
    ax2.grid(True, color=GRID, linewidth=0.7)
    _style_axes(ax2)
    ax2.legend(fontsize=8.5, frameon=False)
    fig.tight_layout()
    fig.savefig(path, dpi=130, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def main() -> None:
    import tempfile

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="dkx_docs_figs_") as tmp:
        work_dir = Path(tmp)

        print("[1/3] |B| contour (W7-X, geometryScheme 4)")
        bmag_path = OUT_DIR / "bmag_contour_w7x.png"
        bmag_contour_w7x(bmag_path)
        _report(bmag_path)

        print("[2/3] transport coefficients vs collisionality (RHSMode 3)")
        transport_path = OUT_DIR / "transport_coeff_vs_collisionality.png"
        transport_coeff_vs_collisionality(transport_path, work_dir)
        _report(transport_path)

        print("[3/3] ambipolar E_r roots (J_r = sum_s Z_s Gamma_s = 0)")
        ambipolar_path = OUT_DIR / "ambipolar_er_roots.png"
        ambipolar_er_roots(ambipolar_path, work_dir)
        _report(ambipolar_path)

    print("done: 3 documentation figures under docs/_static/figures/docs/")


if __name__ == "__main__":
    main()
