"""Schur-complement and moment-coupling preconditioner package."""

from __future__ import annotations

from .profile_response import (
    ActiveNativeFieldSplitSparseCoarsePolicy,
    ActiveNativeStackPolicy,
    ActiveSparseCoarseResidualPolicy,
    RHS1SchurPreconditionerBuilders,
    RHS1StructuredFullCSRPreconditioner,
    append_adaptive_residual_basis_csc,
    build_active_native_xell_coarse_window_basis_csc,
    build_block_schur_preconditioner,
    build_coarse_residual_basis_csc,
    build_diagonal_schur_preconditioner,
    build_jacobi_preconditioner,
    build_rhs1_schur_preconditioner,
    build_x_xi_block_schur_preconditioner,
    build_xi_block_schur_preconditioner,
    canonical_schur_base_kind,
    coarse_residual_config,
    coarse_surface_mode_count,
    coarse_surface_modes,
    estimate_coarse_residual_nbytes,
    estimate_x_xi_block_inverse_nbytes,
    estimate_xblock_tz_low_l_factor_nbytes,
    estimate_xi_block_inverse_nbytes,
    estimate_zeta_block_inverse_nbytes,
    resolve_active_native_field_split_sparse_coarse_policy,
    resolve_active_native_stack_policy,
    resolve_active_sparse_coarse_residual_policy,
    safe_inverse_diagonal,
    xblock_tz_low_l_config,
)

__all__ = (
    "ActiveNativeFieldSplitSparseCoarsePolicy",
    "ActiveNativeStackPolicy",
    "ActiveSparseCoarseResidualPolicy",
    "RHS1SchurPreconditionerBuilders",
    "RHS1StructuredFullCSRPreconditioner",
    "append_adaptive_residual_basis_csc",
    "build_active_native_xell_coarse_window_basis_csc",
    "build_block_schur_preconditioner",
    "build_coarse_residual_basis_csc",
    "build_diagonal_schur_preconditioner",
    "build_jacobi_preconditioner",
    "build_rhs1_schur_preconditioner",
    "build_x_xi_block_schur_preconditioner",
    "build_xi_block_schur_preconditioner",
    "canonical_schur_base_kind",
    "coarse_residual_config",
    "coarse_surface_mode_count",
    "coarse_surface_modes",
    "estimate_coarse_residual_nbytes",
    "estimate_x_xi_block_inverse_nbytes",
    "estimate_xblock_tz_low_l_factor_nbytes",
    "estimate_xi_block_inverse_nbytes",
    "estimate_zeta_block_inverse_nbytes",
    "resolve_active_native_field_split_sparse_coarse_policy",
    "resolve_active_native_stack_policy",
    "resolve_active_sparse_coarse_residual_policy",
    "safe_inverse_diagonal",
    "xblock_tz_low_l_config",
)
