"""Ambipolar radial electric field: scan Er, then solve J_r(Er) = 0 with sfincs_jax.er.

What this example teaches:
  - the ambipolarity workflow: in a stellarator the species' radial fluxes
    depend independently on Er, and the physical Er is the root of the radial
    current J_r(Er) = sum_s Z_s Gamma_s(Er) = 0,
  - how to evaluate the radial current at one Er with ``sfincs_jax.er.radial_current``
    (one canonical drift-kinetic solve) and map Gamma_s(Er),
  - how to find the ambipolar root with ``sfincs_jax.er.find_ambipolar_er`` — the
    Fortran-parity Brent solver (bracket expansion, warm starts, ion/electron/
    unstable classification) that replaces a hand-written bisection,
  - how to plot Gamma_s(Er) and the residual with the root marked.

Physics context: unlike tokamaks, non-axisymmetric (stellarator) magnetic
fields are not intrinsically ambipolar: the neoclassical particle fluxes of
ions and electrons respond differently to the radial electric field, so a
radial current would flow unless Er adjusts to the ambipolar root.  Solving
J_r(Er)=0 selects the "ion root" or "electron root" that sets rotation and
impurity transport in devices like W7-X and LHD [M. Landreman, H. M. Smith,
A. Mollen and P. Helander, Phys. Plasmas 21, 042503 (2014); SFINCS technical
documentation, https://github.com/landreman/sfincs].  Here a small helical
ripple is added to a model field (geometryScheme=1) and an ion+electron pair
is scanned over Er; the E x B drift enters the kinetic equation through the
DKES collisionality-like term (useDKESExBDrift).

The ambipolar root is found by ``sfincs_jax.er.find_ambipolar_er``, which mirrors
SFINCS Fortran v3 ``ambipolarSolver.F90`` (option 2 Brent) and additionally
exposes a differentiable root ``sfincs_jax.er.ambipolar_er`` (see the autodiff
examples) so ``jax.grad`` can flow through the ambipolar Er.

Expected runtime: ~25 s on a laptop CPU (the first solve compiles; each further
Er point reuses the compiled kernels at ~0.4 s each).

Run:
  python examples/ambipolar_er_scan.py
"""

import os
from pathlib import Path

import h5py
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from sfincs_jax import er as er_solver
from sfincs_jax.run import run_profile

# ----------------------------------------------------------------------------
# Parameters
# ----------------------------------------------------------------------------
CI = os.environ.get("SFINCS_JAX_CI") == "1"  # shrink resolution for CI

ER_BRACKET = (-3.0, 1.0)          # Er search bracket (normalized deck units)
ER_SCAN = np.linspace(*ER_BRACKET, 5 if CI else 7)  # coarse scan for the plot

# Resolution (small non-axisymmetric case; PAS collisions keep tier 1 active).
N_THETA = 7 if CI else 11
N_ZETA = 7 if CI else 11
N_XI = 8 if CI else 16
N_L = 4
N_X = 3 if CI else 5

DECK_TEMPLATE = """! Er-scan deck generated by examples/ambipolar_er_scan.py
&general
/
&geometryParameters
  geometryScheme = 1
  inputRadialCoordinate = 3
  rN_wish = 0.3
  B0OverBBar = 1.0
  GHat = 1.0
  IHat = 0.0
  iota = 1.31
  epsilon_t = 0.1
  epsilon_h = 0.05      ! helical ripple: the field is NOT intrinsically ambipolar
  helicity_l = 2
  helicity_n = 5
  psiAHat = 0.045
  aHat = 0.1
/
&speciesParameters
  Zs = 1 -1
  mHats = 1.0 0.000545509
  nHats = 1.0 1.0
  THats = 1.0 1.0
  dNHatdrHats = -0.5 -0.5
  dTHatdrHats = -1.0 -1.0
/
&physicsParameters
  Delta = 4.5694d-3
  alpha = 1.0
  nu_n = 8.4774d-3
  Er = {er}             ! the scan variable
  collisionOperator = 1
  includeXDotTerm = .false.
  includeElectricFieldTermInXiDot = .false.
  useDKESExBDrift = .true.
  includePhi1 = .false.
/
&resolutionParameters
  Ntheta = {n_theta}
  Nzeta = {n_zeta}
  Nxi = {n_xi}
  NL = {n_l}
  Nx = {n_x}
  solverTolerance = 1d-10
/
&otherNumericalParameters
  Nxi_for_x_option = 0
/
"""

OUT_DIR = Path(__file__).parent / "output"
H5_PATH = OUT_DIR / "ambipolar_er_scan.sfincsOutput.h5"
PLOT_PATH = OUT_DIR / "ambipolar_er_scan.png"


def write_deck(er: float) -> Path:
    """Write the input.namelist for one Er and return its path."""
    deck = OUT_DIR / "ambipolar_er_scan.input.namelist"
    deck.write_text(
        DECK_TEMPLATE.format(
            er=er, n_theta=N_THETA, n_zeta=N_ZETA, n_xi=N_XI, n_l=N_L, n_x=N_X
        )
    )
    return deck


# ----------------------------------------------------------------------------
# 1) Coarse scan: map Gamma_s(Er) and J_r(Er) with sfincs_jax.er.radial_current
# ----------------------------------------------------------------------------
print("=== examples/ambipolar_er_scan.py ===")
print("Step 1: coarse Er scan (one canonical solve per Er via er.radial_current)")
print("  geometry:   model stellarator (epsilon_t=0.1, epsilon_h=0.05, l=2, n=5)")
print("  species:    ions (Z=+1) + electrons, PAS collisions, DKES ExB drift")
print(f"  resolution: Ntheta={N_THETA} Nzeta={N_ZETA} Nxi={N_XI} Nx={N_X} (CI={CI})")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Build the shape-stable ambipolar problem once (base operator + Er->dPhiHat
# conversion), then reuse it at every Er with a warm start threaded through.
problem = er_solver.prepare(write_deck(0.0), er_bracket=ER_BRACKET)

print(f"  {'Er':>8} {'Gamma_ions':>14} {'Gamma_electrons':>16} {'J_r = sum Z*Gamma':>18}")
scan_gamma, scan_jr, warm = [], [], None
for er in ER_SCAN:
    j_r, gamma, state = er_solver.radial_current(
        problem, float(er),
        x0=(warm.x if warm else None), recycle=(warm.recycle if warm else None),
    )
    warm = state
    gamma = np.asarray(gamma, dtype=np.float64)
    scan_gamma.append(gamma)
    scan_jr.append(float(j_r))
    print(f"  {er:>8.3f} {gamma[0]:>14.6e} {gamma[1]:>16.6e} {float(j_r):>18.6e}")
scan_gamma = np.asarray(scan_gamma)
scan_jr = np.asarray(scan_jr)

# ----------------------------------------------------------------------------
# 2) Solve for the ambipolar root with the library Brent solver
# ----------------------------------------------------------------------------
print("Step 2: ambipolar root via er.find_ambipolar_er (Fortran-parity Brent)")
result = er_solver.find_ambipolar_er(
    write_deck(0.0), er_bracket=ER_BRACKET, max_iter=20, emit=None
)
if not result.converged or result.er is None:
    raise SystemExit(f"ambipolar solve failed: {result.status} ({result.message})")
er_root = float(result.er)
gamma_root = np.asarray(result.per_species_flux, dtype=np.float64)
print(f"  ambipolar root: Er = {er_root:.4f}  (J_r = {result.radial_current:.3e}, "
      f"{len(result.iterations)} solves)")
print(f"  root classified as: {result.root_type} root")
print(f"  all roots in bracket: {[(round(r.er, 3), r.root_type) for r in result.roots]}")

# ----------------------------------------------------------------------------
# 3) One final solve at the root, writing + reading back the sfincsOutput file
# ----------------------------------------------------------------------------
print("Step 3: writing the root run's h5 output and reading it back")
run_profile(write_deck(er_root), solve_method="auto", emit=None, out_path=H5_PATH)
with h5py.File(H5_PATH, "r") as f:
    er_h5 = float(np.asarray(f["Er"][...]))
    gamma_h5 = np.asarray(f["particleFlux_vm_psiHat"][...], dtype=np.float64).reshape(-1)
print(f"  read back from h5: Er = {er_h5:.4f}")
print(f"  read back from h5: particleFlux_vm_psiHat = {gamma_h5}")

# ----------------------------------------------------------------------------
# 4) Plot Gamma_s(Er) and the residual with the ambipolar root marked
# ----------------------------------------------------------------------------
print("Step 4: plotting")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9.5, 3.8))
ax1.plot(ER_SCAN, scan_gamma[:, 0], "o-", label=r"$\Gamma_i$ (ions)")
ax1.plot(ER_SCAN, scan_gamma[:, 1], "s-", label=r"$\Gamma_e$ (electrons)")
ax1.axvline(er_root, color="k", ls="--", lw=1, label=f"ambipolar $E_r$={er_root:.2f}")
ax1.set_xlabel(r"$E_r$")
ax1.set_ylabel(r"$\Gamma_s$ (particleFlux_vm_psiHat)")
ax1.set_title("species fluxes vs $E_r$")
ax1.legend()
ax2.plot(ER_SCAN, scan_jr, "o-", color="tab:red")
ax2.axhline(0.0, color="k", lw=1)
ax2.plot([er_root], [result.radial_current], "k*", ms=14, label=f"root $E_r$={er_root:.2f}")
ax2.set_xlabel(r"$E_r$")
ax2.set_ylabel(r"$J_r = \sum_s Z_s \Gamma_s$")
ax2.set_title(f"radial current and its {result.root_type} root")
ax2.legend()
fig.tight_layout()
fig.savefig(PLOT_PATH, dpi=140)
plt.close(fig)

# ----------------------------------------------------------------------------
# 5) Final results
# ----------------------------------------------------------------------------
print("=== Final results ===")
print(f"  ambipolar root: Er = {er_root:.4f}  ({result.root_type} root)")
print(f"  J_r at the root = {result.radial_current:.6e}")
print(f"  Gamma_ions at the root = {gamma_root[0]:.6e}")
print(f"  Gamma_electrons at the root = {gamma_root[1]:.6e}")
print(f"  total drift-kinetic solves (root find): {len(result.iterations)}")
print(f"  Saved plot: {PLOT_PATH}")
print(f"  Wrote output file: {H5_PATH.name}")
print("Done: examples/ambipolar_er_scan.py")
