"""Autodiff tour: exact derivatives of kinetic outputs through the implicit solve.

What this example teaches:
  - what is differentiable in sfincs_jax: the pure-function route
    (parse text -> KineticOperator -> solve(differentiable=True) ->
    profile_moments_from_operator) is a JAX-traceable pipeline end to end,
  - how to thread a physics parameter through the operator pytree with
    ``dataclasses.replace`` (here THat and the Er-like dPhiHat/dpsiHat scalar),
  - how to get gradients with ``jax.grad`` / ``jax.jacfwd``, and
  - how to verify every gradient against central finite differences.

Physics context: because SFINCS' drift-kinetic equation is linear in the
distribution function, a solved output (bootstrap current FSABjHat, radial
particle flux, ...) is an implicit function of the physics inputs through
K(p) f = b(p).  sfincs_jax wraps the solve in implicit differentiation
(one extra adjoint/transposed solve reusing the same factorization), so
``jax.grad`` returns machine-accurate sensitivities such as d(FSABjHat)/dTHat
— the building block for ambipolar-root derivatives and stellarator
optimization [M. Landreman, H. M. Smith, A. Mollen and P. Helander, Phys.
Plasmas 21, 042503 (2014); SFINCS technical documentation,
https://github.com/landreman/sfincs].  The temperature enters the streaming,
mirror, and drive terms; dPhiHat/dpsiHat is the Er-like scalar multiplying
the E x B terms and the gradient drive.

Expected runtime: ~40 s on a laptop CPU (each of the two gradient checks
compiles a forward and an adjoint solve, then runs two finite-difference
solves for verification).

Run:
  python examples/gradients_tour.py
"""

import os
from dataclasses import replace
from pathlib import Path

import h5py
import jax
import jax.numpy as jnp
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from sfincs_jax.drift_kinetic import kinetic_operator_from_namelist
from sfincs_jax.inputs import parse_sfincs_input_text
from sfincs_jax.run import profile_moments_from_operator
from sfincs_jax.solve import solve

# ----------------------------------------------------------------------------
# Parameters
# ----------------------------------------------------------------------------
CI = os.environ.get("SFINCS_JAX_CI") == "1"  # shrink resolution for CI

FD_EPS_REL = 1e-6  # central finite-difference relative step

# A tiny single-species PAS case with a helical ripple and a nonzero Er so
# both parameters below have a real effect.  PAS + DKES ExB keeps the tier-1
# structured direct solver (and its exact implicit differentiation) active.
N_THETA = 7 if CI else 9
N_ZETA = 5 if CI else 7
N_XI = 5 if CI else 8
N_X = 3 if CI else 4

DECK_TEXT = f"""! Deck generated by examples/gradients_tour.py
&general
/
&geometryParameters
  geometryScheme = 1
  inputRadialCoordinate = 3
  rN_wish = 0.3
  B0OverBBar = 1.0
  GHat = 1.0
  IHat = 0.0
  iota = 1.31
  epsilon_t = 0.1
  epsilon_h = 0.05
  helicity_l = 2
  helicity_n = 5
  psiAHat = 0.045
  aHat = 0.1
/
&speciesParameters
  Zs = 1
  mHats = 1.0
  nHats = 1.0
  THats = 0.5
  dNHatdrHats = -0.5
  dTHatdrHats = -1.0
/
&physicsParameters
  Delta = 4.5694d-3
  alpha = 1.0
  nu_n = 8.4774d-3
  Er = 0.4
  collisionOperator = 1
  includeXDotTerm = .false.
  includeElectricFieldTermInXiDot = .false.
  useDKESExBDrift = .true.
  includePhi1 = .false.
/
&resolutionParameters
  Ntheta = {N_THETA}
  Nzeta = {N_ZETA}
  Nxi = {N_XI}
  NL = 2
  Nx = {N_X}
  solverTolerance = 1d-12
/
&otherNumericalParameters
  Nxi_for_x_option = 0
/
"""

OUT_DIR = Path(__file__).parent / "output"
H5_PATH = OUT_DIR / "gradients_tour.h5"
PLOT_PATH = OUT_DIR / "gradients_tour.png"

# ----------------------------------------------------------------------------
# 1) Build the operator once via the pure-function route
# ----------------------------------------------------------------------------
print("=== examples/gradients_tour.py ===")
print("Step 1: building the KineticOperator via the pure-function route")
print(f"  resolution: Ntheta={N_THETA} Nzeta={N_ZETA} Nxi={N_XI} Nx={N_X} (CI={CI})")
op0 = kinetic_operator_from_namelist(parse_sfincs_input_text(DECK_TEXT))
print(f"  operator: {op0.n_species} species, matrix size {op0.total_size}, "
      f"PAS collisions, DKES ExB drift")
print(f"  baseline THat = {float(op0.t_hat[0])}, "
      f"dPhiHat/dpsiHat = {float(op0.dphi_hat_dpsi_hat):.6f} (the Er-like scalar)")

# ----------------------------------------------------------------------------
# 2) Differentiable objectives: thread parameters through the operator pytree
# ----------------------------------------------------------------------------
# KineticOperator is a frozen dataclass registered as a JAX pytree, so
# dataclasses.replace() swaps one leaf for a traced value and everything
# downstream (RHS drive, matrix apply, solve, moment integrals) is traced too.
# solve(differentiable=True) wraps the solution in implicit differentiation:
# the backward pass costs one transposed solve reusing the same factors.
#
# NOTE (what finite differences see): the PAS collision matrices are built
# eagerly when the operator is constructed, so replacing t_hat afterwards
# does NOT rebuild them — both jax.grad and the finite differences below
# differentiate the same fixed-collisionality function, which is exactly what
# makes them comparable.


def fsab_j_hat(t_hat_scalar):
    """Bootstrap current <j.B> as a function of the (single) species THat."""
    op = replace(op0, t_hat=jnp.reshape(t_hat_scalar, (1,)))
    result = solve(op, op.rhs(), method="block_tridiagonal", differentiable=True)
    return profile_moments_from_operator(op, result.x)["FSABjHat"]


def particle_flux(dphi_scalar):
    """Radial particle flux as a function of the Er-like dPhiHat/dpsiHat scalar."""
    op = replace(
        op0,
        dphi_hat_dpsi_hat=jnp.asarray(dphi_scalar),  # RHS gradient drive
        dphi_hat_dpsi_hat_kinetic=jnp.asarray(dphi_scalar),  # ExB terms in K
    )
    result = solve(op, op.rhs(), method="block_tridiagonal", differentiable=True)
    return profile_moments_from_operator(op, result.x)["particleFlux_vm_psiHat"][0]


# ----------------------------------------------------------------------------
# 3) Gradients via jax.grad / jax.jacfwd, verified against finite differences
# ----------------------------------------------------------------------------
print("Step 2: d(FSABjHat)/d(THat) via jax.grad (reverse mode)")
t0 = float(op0.t_hat[0])
grad_t = float(jax.grad(fsab_j_hat)(jnp.asarray(t0)))
eps = FD_EPS_REL * max(1.0, abs(t0))
fd_t = float(
    (fsab_j_hat(jnp.asarray(t0 + eps)) - fsab_j_hat(jnp.asarray(t0 - eps))) / (2.0 * eps)
)
print(f"  jax.grad           = {grad_t:.10e}")
print(f"  finite differences = {fd_t:.10e}")

print("Step 3: d(particleFlux)/d(dPhiHat/dpsiHat) via jax.jacfwd (forward mode)")
d0 = float(op0.dphi_hat_dpsi_hat)
grad_e = float(jax.jacfwd(particle_flux)(jnp.asarray(d0)))
eps_e = FD_EPS_REL * max(1.0, abs(d0))
fd_e = float(
    (particle_flux(jnp.asarray(d0 + eps_e)) - particle_flux(jnp.asarray(d0 - eps_e)))
    / (2.0 * eps_e)
)
print(f"  jax.jacfwd         = {grad_e:.10e}")
print(f"  finite differences = {fd_e:.10e}")

rows = (
    ("d(FSABjHat)/d(THat)", grad_t, fd_t),
    ("d(particleFlux)/d(dPhiHatdpsiHat)", grad_e, fd_e),
)
print("Step 4: gradient verification table")
print(f"  {'quantity':>34} {'autodiff':>16} {'finite diff':>16} {'rel. difference':>16}")
rel_errs = []
for name, ad, fd in rows:
    rel = abs(ad - fd) / max(abs(fd), 1e-300)
    rel_errs.append(rel)
    print(f"  {name:>34} {ad:>16.8e} {fd:>16.8e} {rel:>16.3e}")
    if not (np.isfinite(ad) and rel < 1e-4):
        raise SystemExit(f"gradient check FAILED for {name}: rel. difference {rel:.3e}")
print("  all gradients verified against central finite differences")

# ----------------------------------------------------------------------------
# 4) Save the comparison to HDF5, read it back, and plot
# ----------------------------------------------------------------------------
print("Step 5: writing the comparison table to HDF5 and plotting")
OUT_DIR.mkdir(parents=True, exist_ok=True)
with h5py.File(H5_PATH, "w") as f:
    f.create_dataset("names", data=np.array([r[0] for r in rows], dtype="S"))
    f.create_dataset("autodiff", data=np.array([r[1] for r in rows]))
    f.create_dataset("finite_difference", data=np.array([r[2] for r in rows]))
    f.create_dataset("relative_difference", data=np.array(rel_errs))
with h5py.File(H5_PATH, "r") as f:
    ad_back = np.asarray(f["autodiff"][...])
print(f"  read back from h5: autodiff = {ad_back}")

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9.5, 3.8))
idx = np.arange(len(rows))
width = 0.38
ax1.bar(idx - width / 2, [abs(r[1]) for r in rows], width, label="|autodiff|")
ax1.bar(idx + width / 2, [abs(r[2]) for r in rows], width, label="|finite diff|")
ax1.set_yscale("log")
ax1.set_xticks(idx)
ax1.set_xticklabels(["dFSABjHat/dTHat", "dGamma/dPhi'"], rotation=10)
ax1.set_title("gradient magnitudes")
ax1.legend()
ax2.bar(idx, rel_errs, color="tab:green")
ax2.set_yscale("log")
ax2.set_xticks(idx)
ax2.set_xticklabels(["dFSABjHat/dTHat", "dGamma/dPhi'"], rotation=10)
ax2.set_title("autodiff vs finite-difference rel. difference")
fig.tight_layout()
fig.savefig(PLOT_PATH, dpi=140)
plt.close(fig)

# ----------------------------------------------------------------------------
# 5) Final results
# ----------------------------------------------------------------------------
print("=== Final results ===")
print(f"  d(FSABjHat)/d(THat)               = {grad_t:.8e} (rel. diff vs FD {rel_errs[0]:.2e})")
print(f"  d(particleFlux)/d(dPhiHatdpsiHat) = {grad_e:.8e} (rel. diff vs FD {rel_errs[1]:.2e})")
print(f"  Saved plot: {PLOT_PATH}")
print(f"  Wrote output file: {H5_PATH.name}")
print("Done: examples/gradients_tour.py")
