"""Two-species Fokker-Planck run on real W7-X Boozer geometry (.bc file).

What this example teaches:
  - how to point a namelist at a real Boozer-coordinate equilibrium file
    (geometryScheme=11, the ``w7x_standardConfig.bc`` file that ships with the
    SFINCS repository; dkx fetches and caches it automatically),
  - how full Fokker-Planck (collisionOperator=0) multi-species runs work,
  - how the ``solve_method="auto"`` three-tier solver policy picks its tier,
    and how to ask *why* (``dkx.solve.tier1_available``),
  - how to plot the density/pressure perturbations of f1 on the flux surface.

Physics context: Wendelstein 7-X is a stellarator, so its magnetic-field
strength varies both poloidally and toroidally; the resulting class of
helically trapped particles makes neoclassical transport much larger than in
a tokamak at low collisionality (the 1/nu regime), which is why W7-X was
neoclassically optimized.  SFINCS computes these fluxes from the radially
local drift-kinetic equation with the linearized Fokker-Planck operator,
which — unlike pitch-angle scattering — exchanges momentum and energy between
species and within the speed grid [M. Landreman, H. M. Smith, A. Mollen and
P. Helander, Phys. Plasmas 21, 042503 (2014); SFINCS technical documentation,
https://github.com/landreman/sfincs].  The ion+electron pair below is solved
simultaneously; the density perturbation plotted at the end shows the
poloidal+toroidal structure locked to the |B| ripple of W7-X.

Expected runtime: ~30 s on a laptop CPU (~15 s of it JAX compilation).  The
first ever run also downloads the ~1 MB equilibrium archive into
``~/.cache/dkx``.

Run:
  python examples/run_w7x.py
"""

import os
from pathlib import Path

import h5py
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from dkx.run import run_profile
from dkx.solve import tier1_available

# ----------------------------------------------------------------------------
# Parameters
# ----------------------------------------------------------------------------
CI = os.environ.get("DKX_CI") == "1"  # shrink resolution for CI

EQUILIBRIUM = "w7x_standardConfig.bc"  # resolved via the dkx data cache
RN_WISH = 0.5  # surface at r/a = 0.5

# Resolution: intentionally small so the example runs in seconds.  Production
# W7-X runs use Ntheta~25, Nzeta~39, Nxi~70+, Nx~7 (see the Fortran decks in
# examples/sfincs_examples/filteredW7XNetCDF_2species_noEr).
N_THETA = 7 if CI else 11
N_ZETA = 9 if CI else 13
N_XI = 8 if CI else 12
N_L = 4
N_X = 4 if CI else 5
SOLVER_TOLERANCE = 1e-6 if CI else 1e-8

# Ions (Z=1) and electrons, equal temperatures, same normalized gradients.
DECK_TEXT = f"""! W7-X 2-species Fokker-Planck deck generated by examples/run_w7x.py
&general
/
&geometryParameters
  geometryScheme = 11              ! Boozer-coordinate .bc file
  equilibriumFile = "{EQUILIBRIUM}"
  inputRadialCoordinate = 3        ! rN
  rN_wish = {RN_WISH}
/
&speciesParameters
  Zs = 1 -1
  mHats = 1.0 0.000545509
  nHats = 1.0 1.0
  THats = 1.0 1.0
  dNHatdrHats = -0.5 -0.5
  dTHatdrHats = -2.0 -2.0
/
&physicsParameters
  Delta = 4.5694d-3
  alpha = 1.0
  nu_n = 8.4774d-3
  Er = 0.0
  collisionOperator = 0            ! 0 = full linearized Fokker-Planck
  includeXDotTerm = .false.
  includeElectricFieldTermInXiDot = .false.
  useDKESExBDrift = .false.
  includePhi1 = .false.
/
&resolutionParameters
  Ntheta = {N_THETA}
  Nzeta = {N_ZETA}
  Nxi = {N_XI}
  NL = {N_L}
  Nx = {N_X}
  solverTolerance = {SOLVER_TOLERANCE}
/
&otherNumericalParameters
  Nxi_for_x_option = 0
/
&preconditionerOptions
/
"""

OUT_DIR = Path(__file__).parent / "output"
DECK_PATH = OUT_DIR / "run_w7x.input.namelist"
H5_PATH = OUT_DIR / "run_w7x.sfincsOutput.h5"
PLOT_PATH = OUT_DIR / "run_w7x.png"

# ----------------------------------------------------------------------------
# 1) Write the deck; the .bc equilibrium resolves through the data cache
# ----------------------------------------------------------------------------
print("=== examples/run_w7x.py ===")
print("Step 1: writing the input.namelist (real W7-X Boozer geometry)")
print(f"  equilibrium: {EQUILIBRIUM} (geometryScheme=11, auto-fetched/cached)")
print(f"  surface:     rN = {RN_WISH}")
print("  species:     ions (Z=+1) + electrons, full Fokker-Planck collisions")
print(f"  resolution:  Ntheta={N_THETA} Nzeta={N_ZETA} Nxi={N_XI} Nx={N_X} (CI={CI})")
OUT_DIR.mkdir(parents=True, exist_ok=True)
DECK_PATH.write_text(DECK_TEXT)
print(f"  wrote namelist: {DECK_PATH}")

# ----------------------------------------------------------------------------
# 2) Solve with the auto policy (prints the Fortran-parity console flow)
# ----------------------------------------------------------------------------
print("Step 2: solving with run_profile(solve_method='auto')")
run = run_profile(DECK_PATH, solve_method="auto", out_path=H5_PATH)

# The auto policy has three tiers: tier 1 (structured direct block-Thomas,
# "block_tridiagonal") for the PAS/DKES family, tier 2 (recycled GCROT/FGMRES
# Krylov, "gcrot") when the operator couples (species, x) densely, tier 3
# (host direct, "direct") as a loud fallback.  Ask why tier 1 was rejected:
tier1_ok, tier1_reason = tier1_available(run.operator)
print(f"  Solver tier used: {run.solve_result.method}")
print(f"  tier-1 structured direct applicable: {tier1_ok}")
print(f"  policy reason: {tier1_reason if not tier1_ok else 'tier 1 supported'}")
if run.solve_result.iterations is not None:
    print(f"  Krylov iterations: {run.solve_result.iterations}")
print(f"  residual norm: {float(np.max(np.asarray(run.solve_result.residual_norms))):.3e}")

# ----------------------------------------------------------------------------
# 3) Per-species flux table from the moments dictionary
# ----------------------------------------------------------------------------
print("Step 3: per-species flux table (h5-named keys of run.moments)")
labels = ("ions", "electrons")
gamma = np.asarray(run.moments["particleFlux_vm_psiHat"])
q_flux = np.asarray(run.moments["heatFlux_vm_psiHat"])
fsab_flow = np.asarray(run.moments["FSABFlow"])
print(f"  {'species':>10} {'particleFlux_vm_psiHat':>24} {'heatFlux_vm_psiHat':>20} {'FSABFlow':>14}")
for s, name in enumerate(labels):
    print(f"  {name:>10} {gamma[s]:>24.6e} {q_flux[s]:>20.6e} {fsab_flow[s]:>14.6e}")

# ----------------------------------------------------------------------------
# 4) Plot density/pressure perturbations on the surface + the flux table
# ----------------------------------------------------------------------------
print("Step 4: reading the h5 output back and plotting surface perturbations")
with h5py.File(H5_PATH, "r") as f:
    theta = np.asarray(f["theta"][...], dtype=np.float64)
    zeta = np.asarray(f["zeta"][...], dtype=np.float64)
    n_periods = int(np.asarray(f["NPeriods"][...]))
print(f"  read back from h5: NPeriods = {n_periods}, "
      f"Ntheta x Nzeta = {theta.size} x {zeta.size}")

dens = np.asarray(run.moments["densityPerturbation"])  # (species, theta, zeta)
pres = np.asarray(run.moments["pressurePerturbation"])

fig, axes = plt.subplots(2, 2, figsize=(10.0, 6.4))
for row, (field, title) in enumerate(
    ((dens, "density perturbation"), (pres, "pressure perturbation"))
):
    for col, name in enumerate(labels):
        ax = axes[row, col]
        pcm = ax.pcolormesh(zeta, theta, field[col], shading="auto", cmap="RdBu_r")
        fig.colorbar(pcm, ax=ax)
        ax.set_xlabel(r"$\zeta$ (one field period)")
        ax.set_ylabel(r"$\theta$")
        ax.set_title(f"{name}: {title}")
fig.suptitle(f"W7-X rN={RN_WISH}: perturbations of f1 on the flux surface")
fig.tight_layout()
fig.savefig(PLOT_PATH, dpi=140)
plt.close(fig)

# ----------------------------------------------------------------------------
# 5) Final results
# ----------------------------------------------------------------------------
print("=== Final results ===")
print(f"  Solver tier used: {run.solve_result.method}")
for s, name in enumerate(labels):
    print(f"  particleFlux_vm_psiHat[{name}] = {gamma[s]:.6e}")
    print(f"  heatFlux_vm_psiHat[{name}]     = {q_flux[s]:.6e}")
print(f"  FSABjHat = {float(np.asarray(run.moments['FSABjHat'])):.6e}")
print(f"  Saved plot: {PLOT_PATH}")
print(f"  Wrote output file: {H5_PATH.name}")
print("Done: examples/run_w7x.py")
