"""Monoenergetic transport matrix (RHSMode=3) versus collisionality.

What this example teaches:
  - how RHSMode=3 works: SFINCS drops the species/speed physics and solves the
    monoenergetic (single-speed) drift-kinetic equation for two right-hand
    sides at once, returning a 2x2 transport matrix,
  - how to scan a physics parameter (here the normalized collisionality
    nuPrime) by regenerating the deck and calling ``run_transport_matrix``,
  - how to extract and tabulate the D11-like (radial transport) and D31-like
    (bootstrap/Ware coupling) matrix entries and plot them log-log.

Physics context: monoenergetic transport coefficients are the classic way to
characterize a magnetic configuration's neoclassical transport (the DKES code
popularized them).  The 2x2 matrix L maps the thermodynamic drives (radial
gradient drive, parallel electric field) to the responses (radial particle
flux, parallel flow): L11 is the radial diffusion coefficient (D11-like),
L21=L12 the bootstrap/Ware-pinch coupling (D31-like, Onsager-symmetric), and
L22 the parallel conductivity coefficient.  Scanning nuPrime maps out the
collisionality regimes — in a non-axisymmetric field the radial coefficient
famously grows as 1/nu at low collisionality [M. Landreman, H. M. Smith,
A. Mollen and P. Helander, Phys. Plasmas 21, 042503 (2014); SFINCS technical
documentation, https://github.com/landreman/sfincs; W. I. van Rij and
S. P. Hirshman, Phys. Fluids B 1, 563 (1989) for DKES].

Expected runtime: ~10 s on a laptop CPU (the first solve compiles; each
further nuPrime point reuses the compiled kernels and takes ~0.2 s).

Run:
  python examples/transport_coefficients.py
"""

import os
import time
from pathlib import Path

import h5py
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from dkx.run import run_transport_matrix

# ----------------------------------------------------------------------------
# Parameters
# ----------------------------------------------------------------------------
CI = os.environ.get("DKX_CI") == "1"  # shrink resolution for CI

# Collisionality scan: one decade of nuPrime, 5 points (3 in CI).
NU_PRIMES = np.logspace(-2.0, -1.0, 3 if CI else 5)

# Resolution of the monoenergetic pitch-angle grid (Nx=1 is forced by RHSMode=3).
N_THETA = 9 if CI else 13
N_ZETA = 9 if CI else 13
N_XI = 8 if CI else 16
N_L = 4

# Three-helicity model field (geometryScheme=1) with a strong helical ripple,
# i.e. a deliberately non-axisymmetric configuration so the 1/nu physics shows.
DECK_TEMPLATE = """! RHSMode=3 deck generated by examples/transport_coefficients.py
&general
  RHSMode = 3          ! monoenergetic 2x2 transport matrix
/
&geometryParameters
  geometryScheme = 1
  epsilon_t = -0.07053
  epsilon_h = 0.05067
  iota = 0.4542
  GHat = 3.7481
  IHat = 0.0
  helicity_l = 2
  helicity_n = 10
  B0OverBBar = 1.0
/
&speciesParameters
  ! RHSMode=3 ignores species inputs: the equation is monoenergetic.
/
&physicsParameters
  nuPrime = {nu_prime}  ! normalized collisionality (the scan variable)
  EStar = 0.0           ! normalized radial electric field
  collisionOperator = 1
  includeXDotTerm = .false.
  includeElectricFieldTermInXiDot = .false.
  useDKESExBDrift = .true.
  includePhi1 = .false.
/
&resolutionParameters
  Ntheta = {n_theta}
  Nzeta = {n_zeta}
  Nxi = {n_xi}
  NL = {n_l}
  Nx = 1
  solverTolerance = 1d-10
/
&otherNumericalParameters
  Nxi_for_x_option = 0
/
"""

OUT_DIR = Path(__file__).parent / "output"
H5_PATH = OUT_DIR / "transport_coefficients.sfincsOutput.h5"
PLOT_PATH = OUT_DIR / "transport_coefficients.png"

# ----------------------------------------------------------------------------
# 1) Scan nuPrime, one run_transport_matrix call per point
# ----------------------------------------------------------------------------
print("=== examples/transport_coefficients.py ===")
print("Step 1: scanning the monoenergetic transport matrix over collisionality")
print("  geometry:  three-helicity stellarator model (l=2, n=10 ripple)")
print(f"  scan:      nuPrime in [{NU_PRIMES[0]:.3g}, {NU_PRIMES[-1]:.3g}], "
      f"{NU_PRIMES.size} points (CI={CI})")
print(f"  resolution Ntheta={N_THETA} Nzeta={N_ZETA} Nxi={N_XI} (RHSMode=3 forces Nx=1)")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# NOTE on speed: run_transport_matrix rebuilds the operator per call, but JAX
# caches the compiled solve kernels, so only the first point pays compilation.
# For dense scans the lower-level route pays off even more: build one
# KineticOperator, then reuse the tier-1 factorization across right-hand sides
# (dkx.solve.build_tier1_solver) or warm-start tier-2 Krylov solves by
# passing the previous SolveResult's ``recycle=(C, U)`` pair and ``x0`` to
# dkx.solve.solve — the recycled deflation space makes neighboring
# collisionality points converge in a handful of iterations.
matrices = []
for i, nu_prime in enumerate(NU_PRIMES):
    deck = OUT_DIR / f"transport_coefficients.nu{i}.input.namelist"
    deck.write_text(
        DECK_TEMPLATE.format(
            nu_prime=nu_prime, n_theta=N_THETA, n_zeta=N_ZETA, n_xi=N_XI, n_l=N_L
        )
    )
    t0 = time.perf_counter()
    run = run_transport_matrix(
        deck,
        solve_method="auto",
        emit=None,  # silence the per-run Fortran console flow during the scan
        out_path=H5_PATH if i == NU_PRIMES.size - 1 else None,
    )
    elapsed = time.perf_counter() - t0
    matrices.append(np.asarray(run.transport_matrix))
    print(f"  point {i + 1}/{NU_PRIMES.size}: nuPrime={nu_prime:.4e}  "
          f"method={run.solve_result.method}  ({elapsed:.2f} s)")

matrices = np.asarray(matrices)  # (n_points, 2, 2)

# ----------------------------------------------------------------------------
# 2) Tabulate the matrix entries
# ----------------------------------------------------------------------------
# Row/column convention (diagnostics.F90 normalization): drive 1 = radial
# gradient, drive 2 = parallel electric field; response 1 = radial particle
# flux, response 2 = FSA parallel flow.  So L11 ~ D11 (radial diffusion),
# L21 ~ D31 (bootstrap), L12 ~ Ware pinch (Onsager: L12 = L21), L22 ~ D33.
print("Step 2: transport-matrix entries vs collisionality")
print(f"  {'nuPrime':>12} {'L11 (D11-like)':>16} {'L21 (D31-like)':>16} {'L12':>16} {'L22':>12}")
for nu_prime, mat in zip(NU_PRIMES, matrices):
    print(f"  {nu_prime:>12.4e} {mat[0, 0]:>16.6e} {mat[1, 0]:>16.6e} "
          f"{mat[0, 1]:>16.6e} {mat[1, 1]:>12.4e}")

onsager = np.max(np.abs(matrices[:, 0, 1] - matrices[:, 1, 0]) / np.abs(matrices[:, 1, 0]))
print(f"  max Onsager asymmetry |L12-L21|/|L21| over the scan: {onsager:.2e}")

# ----------------------------------------------------------------------------
# 3) Read the last output file back, then plot the scan log-log
# ----------------------------------------------------------------------------
print("Step 3: reading the last point's h5 output back and plotting")
with h5py.File(H5_PATH, "r") as f:
    # Fortran stores the matrix column-major, so it reads back transposed.
    tm_h5 = np.asarray(f["transportMatrix"][...], dtype=np.float64).T
    nu_prime_h5 = float(np.asarray(f["nuPrime"][...]))
print(f"  read back from h5: nuPrime = {nu_prime_h5:.4e}")
print(f"  read back from h5: transportMatrix[0,0] = {tm_h5[0, 0]:.6e} "
      f"(in-memory {matrices[-1][0, 0]:.6e})")

fig, ax = plt.subplots(figsize=(6.0, 4.2))
ax.loglog(NU_PRIMES, np.abs(matrices[:, 0, 0]), "o-", label=r"$|L_{11}|$ (radial, $D_{11}$-like)")
ax.loglog(NU_PRIMES, np.abs(matrices[:, 1, 0]), "s-", label=r"$|L_{21}|$ (bootstrap, $D_{31}$-like)")
ax.set_xlabel(r"$\nu'$ (normalized collisionality)")
ax.set_ylabel("monoenergetic transport coefficient")
ax.set_title("RHSMode=3 transport matrix vs collisionality")
ax.grid(True, which="both", alpha=0.3)
ax.legend()
fig.tight_layout()
fig.savefig(PLOT_PATH, dpi=140)
plt.close(fig)

# ----------------------------------------------------------------------------
# 4) Final results
# ----------------------------------------------------------------------------
print("=== Final results ===")
print(f"  L11 at nuPrime={NU_PRIMES[0]:.3g}: {matrices[0][0, 0]:.6e}")
print(f"  L11 at nuPrime={NU_PRIMES[-1]:.3g}: {matrices[-1][0, 0]:.6e}")
print(f"  L21 at nuPrime={NU_PRIMES[-1]:.3g}: {matrices[-1][1, 0]:.6e}")
print(f"  Saved plot: {PLOT_PATH}")
print(f"  Wrote output file: {H5_PATH.name}")
print("Done: examples/transport_coefficients.py")
