"""Physics problem packages that orchestrate reusable operators and solvers."""

from __future__ import annotations

from .ambipolar import (
    AmbipolarIteration,
    AmbipolarProblem,
    AmbipolarResult,
    RadialCurrentDerivativeEvaluator,
    RadialCurrentDerivativeResult,
    SfincsJaxEvaluationRecord,
    SfincsJaxRadialCurrentEvaluator,
    brent_ambipolar_root,
    dense_rhs1_vm_radial_current_linear_observable_system,
    finite_difference_radial_current_derivative,
    implicit_linear_radial_current_derivative,
    implicit_linear_radial_current_derivative_from_builder,
    implicit_matrix_free_radial_current_derivative,
    implicit_matrix_free_radial_current_derivative_from_builder,
    matrix_free_radial_current_derivative_provider,
    matrix_free_rhs1_vm_radial_current_linear_observable_system,
    newton_ambipolar_root,
    operator_tangent_from_centered_difference,
    safeguarded_newton_ambipolar_root,
    solve_ambipolar_brent,
    solve_ambipolar_newton,
    solve_ambipolar_safeguarded_newton,
    solve_sfincs_jax_ambipolar_brent,
    validate_fortran_v3_ambipolar_constraints,
)

__all__ = (
    "AmbipolarIteration",
    "AmbipolarProblem",
    "AmbipolarResult",
    "RadialCurrentDerivativeEvaluator",
    "RadialCurrentDerivativeResult",
    "SfincsJaxEvaluationRecord",
    "SfincsJaxRadialCurrentEvaluator",
    "brent_ambipolar_root",
    "dense_rhs1_vm_radial_current_linear_observable_system",
    "finite_difference_radial_current_derivative",
    "implicit_linear_radial_current_derivative",
    "implicit_linear_radial_current_derivative_from_builder",
    "implicit_matrix_free_radial_current_derivative",
    "implicit_matrix_free_radial_current_derivative_from_builder",
    "matrix_free_radial_current_derivative_provider",
    "matrix_free_rhs1_vm_radial_current_linear_observable_system",
    "newton_ambipolar_root",
    "operator_tangent_from_centered_difference",
    "safeguarded_newton_ambipolar_root",
    "solve_ambipolar_brent",
    "solve_ambipolar_newton",
    "solve_ambipolar_safeguarded_newton",
    "solve_sfincs_jax_ambipolar_brent",
    "validate_fortran_v3_ambipolar_constraints",
)
