#!/usr/bin/env python

"""Radial electric field scan (scanType=2).

Called by ``sfincsScan`` when ``!ss scanType = 2``. Creates subdirectories for
each Er value and runs dkx. Configure ``!ss NErs``, ``ErMin``, and
``ErMax`` (or ``dPhiHatd*`` equivalents) in ``input.namelist``.
"""

# This script will not work if called directly.
# From the command line, you should call sfincsScan instead.

import os, inspect
from pathlib import Path
from dkx_driver import run_dkx
from builtins import input

#print ("This is "+ inspect.getfile(inspect.currentframe()))
this_filename = "sfincsScan_2"
print ("This is "+ this_filename)
print ("Beginning a scan of E_r.")

## inputRadialCoordinateForGradients = readVariable("inputRadialCoordinateForGradients","int")

inputRadialCoordinateForGradients = readVariable("inputRadialCoordinateForGradients","int", False)
if inputRadialCoordinateForGradients == None :
    inputRadialCoordinateForGradients = readDefault("inputRadialCoordinateForGradients","int")

NErs = readScanVariable("NErs","int")
if inputRadialCoordinateForGradients==0:
    varName = "dPhiHatdpsiHat"
elif inputRadialCoordinateForGradients==1:
    varName = "dPhiHatdpsiN"
elif inputRadialCoordinateForGradients==2:
    varName = "dPhiHatdrHat"
elif inputRadialCoordinateForGradients==3:
    varName = "dPhiHatdrN"
elif inputRadialCoordinateForGradients==4:
    varName = "Er"
else:
    print ("Error! Invalid inputRadialCoordinateForGradients.")
    exit(1)

generalEr_min = readScanVariable(varName+"Min","float")
generalEr_max = readScanVariable(varName+"Max","float")

generalErs = linspace(generalEr_max, generalEr_min, NErs)

print ("Radial electric field is specified using "+varName)
print ("Here are the "+str(len(generalErs))+" values we will use for this quantity:")
print (generalErs)

directories = [varName+"{:.4g}".format(generalEr) for generalEr in generalErs]
generalErs_copy = list(generalErs)
directories_copy = list(directories)

# See if any runs with the same description already exist.
# This happens if you re-run sfincsScan more than once in the same directory.
for i in range(len(generalErs_copy)):
    directory = directories_copy[i]
    if scan_point_complete(directory):
        print ("Directory "+directory+" has complete output; skipping this run.")
        generalErs.remove(generalErs_copy[i])
        directories.remove(directory)

print ()
print ("Here are the directories that will be created:")
print (directories)

if waitBeforeSubmitting:
    while True:
        #proceed=raw_input("Should I go ahead and launch these "+str(len(generalErs))+" jobs? [y/n] ")
        proceed=input("Should I go ahead and launch these "+str(len(generalErs))+" jobs? [y/n] ")
        if proceed=="y" or proceed=="n":
            break
        print ("You must enter either y or n.")

    if proceed=="n":
        exit(0)

print ("launching runs...")

scan_progress = start_scan_progress(total_runs=len(generalErs), label=this_filename)
prev_dir = None
for runNum in range(len(generalErs)):
    directory = directories[runNum]
    run_started_at = note_scan_run_start(progress=scan_progress, run_index=runNum+1, directory=directory)

    if scan_point_complete(directory):
        continue
    # Retry incomplete points in place, preserving their previous attempt first.
    os.makedirs(directory, exist_ok=True)
    archive_scan_attempt(directory, filename)
    current_dir = Path(directory).resolve()
    configure_krylov_recycle(prev_dir, current_dir)

    # Now copy the input.namelist file:

    #################################################

    input_lines = []
    for line in inputFile:
        if namelistLineContains(line,varName):
##            line = "  "+varName+" = "+str(Ers[runNum])+" ! Set by sfincsScan_2.\n" 
            continue

        if line.strip().find("&physicsParameters") == 0 :
            line += "  "+varName+" = "+str(generalErs[runNum])+" ! Set by sfincsScan_2.\n"
        input_lines.append(line)

    #################################################

    input_path = current_dir / filename
    input_path.write_text("".join(input_lines))
    # One point that will not solve must not discard the rest of the scan.
    point_ok = run_scan_point(
        input_namelist=input_path,
        output_path=current_dir / outputFilename,
        directory=directory,
    )
    note_scan_run_done(progress=scan_progress, run_index=runNum+1, directory=directory, run_started_at=run_started_at, success=point_ok)

    prev_dir = current_dir if point_ok else prev_dir
